apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: my-secrets
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXNAIyM=
